apiVersion: v1
kind: ConfigMap
metadata:
  name: scrolller-api-config
  namespace: scrolller
  labels:
    app: scrolller-api
data:
  NODE_ENV: "development"
  DATABASE_URL: "postgresql://scrolller:scrolller@postgres-service/scrolllerdb"
  COOKIE_NAME: "session"
  REDDIT_URL: "https://reddit.com"
  WEB_URL: "http://localhost:30003"
