apiVersion: v1
kind: ConfigMap
metadata:
  name: scrolller-api-config
  labels:
    app: scrolller-api
data:
  NODE_ENV: "development"
  DATABASE_URL: "postgresql://scrolller:scrolller@localhost:30001/scrolller"
  COOKIE_NAME: "session"
  REDDIT_URL: "https://reddit.com"
  WEB_URL: "http://localhost:30003"
