apiVersion: v1
kind: Service
metadata:
  name: scrolller-web-service
  namespace: scrolller
  labels:
    app: scrolller-web
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30003
  selector:
    app: scrolller-web
